ALTER TABLE ACE_CHANGE_PRODUCT
 DROP PRIMARY KEY CASCADE;
DROP TABLE ACE_CHANGE_PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE ACE_CHANGE_PRODUCT
(
  ID            NUMBER(13),
  CHANGE_ID     NUMBER(10)                      NOT NULL,
  EAN           NUMBER(13)                      NOT NULL,
  NOTIFICATION  CLOB,
  DATA          CLOB,
  ADD_DTIME     DATE                            DEFAULT SYSDATE,
  UPD_DTIME     DATE                            DEFAULT SYSDATE
);

CREATE INDEX ACE_CHANGE_PROD_CHANGE_ID_IDX ON ACE_CHANGE_PRODUCT
(CHANGE_ID)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX PKACE_CHANGE_PRODUCT ON ACE_CHANGE_PRODUCT
(ID)
LOGGING
NOPARALLEL;

CREATE OR REPLACE TRIGGER ACE_CHANGE_PRODUCT_BI
BEFORE INSERT ON ACE_CHANGE_PRODUCT for each row
BEGIN
    IF :new.id IS NULL THEN
        SELECT ACE_CHANGE_PRODUCT_SEQ.nextval INTO :new.id FROM DUAL;
    END IF;
END;
/

DROP PUBLIC SYNONYM ACE_CHANGE_PRODUCT;

CREATE PUBLIC SYNONYM ACE_CHANGE_PRODUCT FOR ACE_CHANGE_PRODUCT;

ALTER TABLE ACE_CHANGE_PRODUCT ADD (
  PRIMARY KEY
 (ID));
