CREATE TABLE [dbo].[ACE_CHANGE_PRODUCT]
(
 [ID]           [numeric]   (13, 0)   NOT NULL AUTO_INCREMENT,
 [CHANGE_ID]    [numeric]   (10, 0)   NOT NULL,
 [EAN]          [numeric]   (13, 0)   NOT NULL, 
 [NOTIFICATION] [clob],
 [DATA]         [clob],
 [ADD_DTIME]    [datetime]            NOT NULL,
 [UPD_DTIME]    [datetime]            NOT NULL,
CONSTRAINT [ACE_CHANGE_PRODUCT] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ACE_CHANGE_PRODUCT] ADD  CONSTRAINT [DF_ACPRD_ADD_DTIME]  DEFAULT (getdate()) FOR [ADD_DTIME]
GO

ALTER TABLE [dbo].[ACE_CHANGE_PRODUCT] ADD  CONSTRAINT [DF_ACPRD_UPD_DTIME]  DEFAULT (getdate()) FOR [UPD_DTIME]
GO