ALTER TABLE ACE_CFG_BUCKET
 DROP PRIMARY KEY CASCADE;
DROP TABLE ACE_CFG_BUCKET CASCADE CONSTRAINTS;

CREATE TABLE ACE_CFG_BUCKET
(
  PROCESS_ID         NUMBER(6)                  NOT NULL,
  API_TYPE           VARCHAR2(3 BYTE)           NOT NULL,
  BUCKET_NM          VARCHAR2(48 BYTE)          NOT NULL,
  ATTR_NM            VARCHAR2(48 BYTE)          NOT NULL,
  TARGET_TABLE_NM    VARCHAR2(48 BYTE)          NOT NULL,
  ATTR_ORA_TYPE      VARCHAR2(24 BYTE)          NOT NULL,
  ATTR_ORA_TYPE_LEN  NUMBER(3),
  ATTR_IS_KEY        CHAR(1 BYTE)               NOT NULL,
  ATTR_XPATH         VARCHAR2(128 BYTE)         NOT NULL,
  ADD_DTIME          DATE                       DEFAULT SYSDATE,
  UPD_DTIME          DATE                       DEFAULT SYSDATE,
  ATTR_IS_XML_BODY   CHAR(1 BYTE)               DEFAULT 'N'
)
;

CREATE UNIQUE INDEX ACE_CFG_BUCKET_PK ON ACE_CFG_BUCKET
(PROCESS_ID, API_TYPE, BUCKET_NM, ATTR_NM)
LOGGING
TABLESPACE INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

DROP PUBLIC SYNONYM ACE_CFG_BUCKET;

CREATE PUBLIC SYNONYM ACE_CFG_BUCKET FOR ACE_CFG_BUCKET;

ALTER TABLE ACE_CFG_BUCKET ADD (
  PRIMARY KEY
 (PROCESS_ID, API_TYPE, BUCKET_NM, ATTR_NM));
